# Generated by Django 5.0.1 on 2024-01-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
